version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      - nginx_logs:/var/log/nginx
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT:-3000}
    command: >
      sh -c "envsubst '$$ACTIVE_POOL $$PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf &&
             rm -f /var/log/nginx/access.log /var/log/nginx/error.log &&
             touch /var/log/nginx/access.log /var/log/nginx/error.log &&
             nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  alert_watcher:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./watcher.py:/app/watcher.py
      - ./requirements.txt:/app/requirements.txt
      - nginx_logs:/var/log/nginx
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
    command: >
      sh -c "pip install -r requirements.txt &&
             echo 'Starting watcher...' &&
             python -u watcher.py"
    depends_on:
      - nginx
    restart: unless-stopped

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:${PORT:-3000}"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT:-3000}

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:${PORT:-3000}"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT:-3000}

volumes:
  nginx_logs:
